# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:
    docker:
      - image: cimg/node:14.16.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn format --check
      - run: yarn lint
      - run: yarn test:run --ci --coverage --reporters=default
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
  stage:
    docker:
      - image: cimg/node:14.16.1-browsers
    steps:
      - checkout
      - run: git checkout staging
      - run: git merge ${CIRCLE_BRANCH}
      - add_ssh_keys:
          fingerprints:
            - "dd:ce:d0:d5:e0:26:e0:79:a3:4c:82:c9:ba:d5:20:c4"
      - run: git push origin staging

workflows:
  version: 2
  deploy_staging:
    jobs:
      - build
      - stage:
        filters:
          branches:
            ignore:
              - staging
              - main