# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:
    docker:
      - image: cimg/node:14.16.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn format --check
      - run: yarn lint
      - run: yarn test:run --ci --coverage --reporters=default
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
  
  deploy:
    machine:
      macos:
        xcode: '9.0'
    steps:
      - run:
          name: Deploy
          command: curl -X POST -d {} ${hook}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main